package com.simformsolutions.practicals.exception;

public class Main {

	public static void main(String[] args) {
		
		try {
			System.out.println("In Try Block");
			
			String a = null;
			
			int i = 4/5;
			
			System.out.println(a.length());
		}
		catch(ArithmeticException e){
			System.out.println("In Arithmetic Exception "+e.getLocalizedMessage());
		}
		catch(Exception e){
			System.out.println("In Generic Exception Block"+e);
		}
		finally {
			System.out.println("Finally block Executed");
		}
		System.out.println("Remaining Code Executed");

	}

}
